markdown: kramdown
highlighter: pygments
permalink: /posts/id-:title.html
excerpt_separator: "<!-- more -->"

github: panxw
author: "潘学文"
name: "潘学文个人博客"
description: ""
url: http://www.panxw.com
domain: panxw.com

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
